---
app:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/projink_demo1"
    password: password
    pool-size: 30
    username: postgres
spring:
  profiles:
    active: spring.profiles.active