---
app:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/projink_demo1_version2"
    password: password
    pool-size: 30
    username: postgres
spring:
  profiles:
    active: spring.profiles.active
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

#  ssl:
#    key-store: www.yunyunshuo.cn.jks
#    key-store-password: wi4c68i26xy84
#    key-store-type: pkcs12
#    key-alias: www.yunyunshuo.cn
#  port: 8443